// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomDataGenerator.Data.Data;

#nullable disable

namespace RandomDataGenerator.ConsoleClient.Migrations
{
    [DbContext(typeof(DataGeneratorContext))]
    [Migration("20221216181546_InitialFileEntriesMigration")]
    partial class InitialFileEntriesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RandomDataGenerator.Domain.DataProcessors.FileEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("FloatingNumber")
                        .HasColumnType("float");

                    b.Property<int>("IntegerNumber")
                        .HasColumnType("int");

                    b.Property<string>("LatinString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RussianString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
